blog/urls.py
from django.conf.urls import url
from blog.views import PostsListView, post_detail_func_view, logout_page, login_page, register

urlpatterns = [
    url(r'^$', PostsListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', post_detail_func_view, name='detail'),
    url(r'^login$', login_page, name="login_p"),
    url(r'^logout$', logout_page, name="logout_p"),
    url(r'^register$', register, name='reg'),
]

calc/urls.py
from django.conf.urls import url
from calc import views

urlpatterns = [
    url(r'^$',views.calculate,name='calc'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from calc import urls as calc_urls
from blog import urls as blog_urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^calc/', include(calc_urls, namespace = "calculate")),
    url(r'^blog/', include(blog_urls,namespace = "blog")),
    url(r'^', include(blog_urls,namespace = "blog"))
]

blog/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    datetime = models.DateTimeField("Дата публикации",auto_now_add=True)
    content = models.TextField(max_length=10000)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return "/blog/%i/" % self.id

class Comment(models.Model):
    autor = models.CharField(max_length=20)
    message = models.TextField(max_length=100)
    datetime = models.DateTimeField("Дата публикации",auto_now=True)
    post = models.ForeignKey(Post)    
 
    def __str__(self):
        return self.message

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['autor','message']

calc/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
         model = User
         fields = ('username', 'email', 'password')

blog/views.py
from blog.models import Post, Comment, CommentForm
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login, authenticate
from django.template.response import TemplateResponse
from blog.forms  import UserForm

# Create your views here.

class PostsListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.order_by('-datetime')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authForm'] = AuthenticationForm()
        return context


def post_detail_func_view(request, pk):
    # Получа объект или ошибку 404
    postForComment = get_object_or_404(Post, id=pk)
    context = {}
    context['post'] = postForComment
    context['comment_list'] = Comment.objects.filter(post=pk)
    template_name = 'blog/post_detail.html'

    if not request.user.is_authenticated():
        context['authForm'] = AuthenticationForm()

    if request.method == 'POST':

        cf = CommentForm(request.POST)
        context['form'] = cf

        if cf.is_valid():
            new_cf = cf.save(commit=False)
            new_cf.post = postForComment
            new_cf.save()
            return HttpResponseRedirect(reverse('blog:detail', args=pk))
    else:
        context['form'] = CommentForm()

    return render(request, template_name, context)


def list_of_page(request):
    return TemplateResponse(request, "blog/index.html", {})


def login_page(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)
    if user:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('blog:list'))
        else:
            return HttpResponse("Your account is disabled.")
    else:
        # print "Invalid login details: {0}, {1}".format(username, password)
        return HttpResponse("Invalid login details supplied.")


def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:list'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request,
                  'blog/register.html',
                  {'user_form': user_form, 'registered': registered})

calc/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json

# Create your views here.
def calculate(request):

    if request.method == "POST":
        value = request.POST.get('value_exp')
        ans =  calculation(value)
        response_data = {}
        response_data['val_exp'] = ans
        return HttpResponse(
            json.dumps(response_data),
            content_type="aplication/json"
        )
    else:
        return render(request,'calc.html')


def calculation(expr):
   return safe_eval(expr)

def safe_eval(expr, symbols={}):
   return eval(expr, dict(__builtins__=None), symbols)

blog/templates/blog/post_detail.html
    {% extends "blog/post_list.html" %}
	{% url 'detail' post.id as the_url %}

    {% block content %}
    <!--Часть с постом -->
 	<p>{{ post.datetime}}</p>
	<h2>{{ post.title}}</h2>
	<p>{{ post.content|safe}}</p>

    <hr>
    <!-- Часть с формой для комментариев -->
    {% if user.is_authenticated %}
    <form action="{{the_url}}" method="post">
    {% csrf_token %}
	<ul>
	{{ form.as_ul }}
	</ul>
	<input type="submit" value="Submit" />
	</form>
	{% else %}
	    <p> Зарегестрируйтесь, что бы оставить комментарий </p>
	{% endif %}

    <!-- Список комментриев -->
	{% for comment in comment_list %}
	    <hr>
	<blockquote>
	<p> {{comment.autor}} <p>
	<p> {{comment.message}} <p>
	</blockquote>
	    <hr>
	{% endfor %}

    {% endblock %}

blog/templates/blog/post_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="/favicon.ico">

    <title>Blog by A.Surov </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}"  rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'blog/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'blog:list' %}">Home</a>
          <a class="blog-nav-item" href="{% url 'calculate:calc' %}">Calculator</a>
        {% if user.is_authenticated %}
            <p class="blog-nav-item">Привет! {{user.username}}</p>
            <a class="blog-nav-item" href= "{% url 'blog:logout_p'  %}">Выйти</a>
        {% else %}
            <form class="blog-nav-item" action= "{% url 'blog:login_p'  %}" method="post">
 	        {% csrf_token %}
            {{ authForm }}
            <input type="submit" value="Войти">
            </form>
             <a class="blog-nav-item" href="{% url 'blog:reg' %}">Регистрация</a>
        {% endif %}

          <!--<a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a>-->
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The  Blog</h1>
        <p class="lead blog-description">Официальный пример блога от меня)</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

            {% block content %}


            {% for post in object_list %}
          <div class="blog-post">
            <h2 class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="blog-post-meta">{{ post.datetime }} </p>
            <p>{{ post.content|safe }}</p>
          </div><!-- /.blog-post -->
            {% empty %}
             <p>Нет постов</p>
            {% endfor %}




          <nav>
            <ul class="pager">
              <li><a href="#">Previous</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </nav>
            {% endblock %}}

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Обо мне</h4>
                <p></p>Маленький блог от амбициозного, начинающего программиста, готового работать сколько угодно, когда угодно за почти любые деньги.:)</p>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
                <li><a href="https://github.com/NetBerst">GitHub</a></li>
                <li><a href="https://vk.com/artemsurov">VKontakte</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'blog/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

blog/templates/blog/posts_list.html
{% block content %}
    {% for post in object_list %}
        <p>{{ post.datetime }}</p>
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p>{{ post.content }}</p>
    {% empty %}
    <p>Нет постов</p>
    {% endfor %}

{% endblock %}

blog/templates/blog/register.html
 {% extends "blog/post_list.html" %}
    {% block content %}
{% if registered %}
        <strong>Спасибо за регистрацию</strong>
        <a href="/">Return to the homepage.</a><br />
        {% else %}

        <form id="user_form" method="post" action="{% url 'blog:reg' %}"
                enctype="multipart/form-data">

            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}


            <input type="submit" name="submit" value="OK" />
        </form>
        {% endif %}
  {% endblock %}

calc/templates/calc.html
{% load staticfiles %}
<!DOCTYPE  html>
<html>
<head>
    <meta charset="utf-8">
    <title>Тут когда-нибудь будет рабочий калькулятор</title>

    </head>
<body>
    <input type="text" id="result" value="" placeholder="результат" readonly><br><br>
    <form id= "num" methot = "POST">
        {% csrf_token %}
        <input type="button" value="0">
        <input type="button" value="1">
        <input type="button" value="2">
        <input type="button" value="3">
        <input type="button" value="4">
        <br>
        <input type="button" value="5">
        <input type="button" value="6">
        <input type="button" value="7">
        <input type="button" value="8">
        <input type="button" value="9">
        <br>
        <input type="button" value="+">
        <input type="button" value="-">
        <input type="button" value="*">
        <input type="button" value="/">

    </form>
        <input type="button" id="clean" value="c">
        <input type="button" id="cleanElm" value="ce">
        <br>
        <input type="button" id="equally" value="=">

    <script src="{% static 'calc/js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'calc/js/source.js' %}"></script>

    <div id="results"></div> <!-- errors go here -->
    </body>
</html>